---
# Number of pod replicas
#   Can be changed if you know what you do.
replicaCount: 1

# Image
#   Array of specification of docker image
#   Repository is docker image location which you need to run.
#   pullPolicy can be Alway or IfNotPresent
image:
  repository: 317583874524.dkr.ecr.ap-southeast-1.amazonaws.com/prayoonorchid-api-nestjs
  tag: develop
  pullPolicy: Always

# Project name
#   String of your project name
nameOverride: dev-prayoonorchid-api-nestjs
fullnameOverride: dev-prayoonorchid-api-nestjs

# Environment References
#   List name of resources which you want to reference.
#   To refer to a configMap or secret resource outside pod.
#
envFrom: {}
  #  configMaps:
  #    - prayoonorchid-api-nestjs
  #  secrets:
  #    - prayoonorchid-api-nestjs

# configMap
#   Array of key, value.
#   Enable to create configMap.
#   The resource name will be same as your project name.
#   Baware of value type is always be string.
configMaps:
  create: false
  data:
    ENV: ""

# secret
#   Array of key, value.
#   Enable to create secret in base64 encoded.
#   The resource name will be same as your project name.
#   Baware of value type is always be string.
secrets:
  create: false
  data:
    USER: ""
    PASS: ""

# Container Port(s)
#   List of ports that your container exposed in dockerfile.
containerPorts:
  - 3000

# Resources Allocation
#   Specify requests for allocation resources and limits for maximum of resources usage
resources: {}
#  requests:
#    cpu: 50m
#    memory: 100Mi
#  limits:
#    cpu: 50m
#    memory: 100Mi

# Service
#   Act as load balancer in front of your pod.
#   To forward traffic into your pod.
services:
  - type: ClusterIP
    ports:
      - name: http
        protocol: TCP
        port: 80
        targetPort: 3000

# Ingress Resource
#   Enable to create ingress as your project name.
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "1800s"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800s"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800s"
  rules:
    - host: "dev-prayoonorchid.phoenix-stark.com"
      http:
        paths:
          - path: /api/v1
            backend:
              service:
                port:
                  number: 80
